// EXAMPLE GENERATED BY CHATGPT

// Import the node-fetch library
import fetch from 'node-fetch';
// Using import instead of require given ES6 module (look it up if confused!)

// Example URL to fetch data from
const url = 'https://jsonplacrafafeholder.typicode.com/todos/1';

// Function to fetch data from the URL using promises
function fetchData() {
  fetch(url) // do this 
    .then(response => { // then do this lambda function on what is returned
      if (!response.ok) {
        throw new Error('Network response was not ok ' + response.statusText);
      }
      return response.json();
    })
    .then(data => {
      console.log('Data fetched:', data);
    })
    .catch(error => {
      console.error('There was a problem with the fetch operation:', error);
    });
}

// Call the fetchData function
fetchData();